
services:
  backend:
    build: ./server
    ports:
      - "3001:3001"


  frontend:
    build: ./frontend

    ports:
      - "3000:3000"  # Ou "3005:3000", dependendo da necessidade
    depends_on:
      - backend



